import React from 'react';

export interface FAQItem {
  question: string;
  answer: string;
}

interface FAQBlockProps {
  items: FAQItem[];
  heading?: string;
  eyebrow?: string;
  className?: string;
  theme?: 'light' | 'dark';
}

/**
 * FAQBlock renders a Q&A list with semantic markup ready for FAQPage schema.
 * The schema itself is generated by `buildFAQSchema(items)` in `lib/seo.ts`
 * and injected via the page-level <SEO jsonLd={...} /> prop — this component
 * is presentation only.
 */
export const FAQBlock: React.FC<FAQBlockProps> = ({
  items,
  heading = 'Frequently Asked Questions',
  eyebrow = 'FAQ',
  className = '',
  theme = 'dark',
}) => {
  if (!items || items.length === 0) return null;
  const isLight = theme === 'light';

  return (
    <section
      className={`py-20 md:py-24 ${className}`}
      aria-labelledby="faq-heading"
    >
      <div className="mx-auto max-w-3xl px-6">
        <p className={isLight ? "chapter-eyebrow mb-6" : "mb-3 text-[11px] font-bold uppercase tracking-[0.28em] text-[#F77E0D]"}>
          {eyebrow}
        </p>
        <h2
          id="faq-heading"
          className={isLight ? "mb-10 heading-manuscript text-[clamp(1.75rem,3vw,2.5rem)] text-manuscript-ink" : "mb-10 font-display text-[clamp(1.75rem,3vw,2.5rem)] font-bold tracking-tight text-white"}
        >
          {heading}
        </h2>

        <div className={`divide-y border-y ${isLight ? 'divide-manuscript-parchmentDeep border-manuscript-parchmentDeep' : 'divide-white/[0.07] border-white/[0.07]'}`}>
          {items.map((item, i) => (
            <details
              key={i}
              className="group py-6"
            >
              <summary
                className="flex cursor-pointer list-none items-start justify-between gap-6 text-left"
              >
                <h3 className={isLight ? "heading-manuscript text-xl text-manuscript-ink group-hover:text-manuscript-rust transition-colors" : "text-[1.05rem] font-semibold leading-snug text-white"}>
                  {item.question}
                </h3>
                <span
                  aria-hidden="true"
                  className={`mt-1 shrink-0 transition-transform duration-200 group-open:rotate-45 ${isLight ? 'text-manuscript-copper' : 'text-[#F77E0D]'}`}
                >
                  +
                </span>
              </summary>
              <p className={`mt-4 max-w-2xl font-manuscriptBody ${isLight ? 'text-[15px] leading-[1.75] text-manuscript-inkMuted' : 'text-[15px] leading-[1.75] text-neutral-400'}`}>
                {item.answer}
              </p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQBlock;