import React from 'react';

export interface FAQItem {
  question: string;
  answer: string;
}

interface FAQBlockProps {
  items: FAQItem[];
  heading?: string;
  eyebrow?: string;
  className?: string;
}

/**
 * FAQBlock renders a Q&A list with semantic markup ready for FAQPage schema.
 * The schema itself is generated by `buildFAQSchema(items)` in `lib/seo.ts`
 * and injected via the page-level <SEO jsonLd={...} /> prop — this component
 * is presentation only.
 */
export const FAQBlock: React.FC<FAQBlockProps> = ({
  items,
  heading = 'Frequently Asked Questions',
  eyebrow = 'FAQ',
  className = '',
}) => {
  if (!items || items.length === 0) return null;

  return (
    <section
      className={`py-20 md:py-24 ${className}`}
      aria-labelledby="faq-heading"
    >
      <div className="mx-auto max-w-3xl px-6">
        <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.28em] text-[#F77E0D]">
          {eyebrow}
        </p>
        <h2
          id="faq-heading"
          className="mb-10 font-display text-[clamp(1.75rem,3vw,2.5rem)] font-bold tracking-tight text-white"
        >
          {heading}
        </h2>

        <div className="divide-y divide-white/[0.07] border-y border-white/[0.07]">
          {items.map((item, i) => (
            <details
              key={i}
              className="group py-6"
            >
              <summary
                className="flex cursor-pointer list-none items-start justify-between gap-6 text-left"
              >
                <h3 className="text-[1.05rem] font-semibold leading-snug text-white">
                  {item.question}
                </h3>
                <span
                  aria-hidden="true"
                  className="mt-1 shrink-0 text-[#F77E0D] transition-transform duration-200 group-open:rotate-45"
                >
                  +
                </span>
              </summary>
              <p className="mt-4 max-w-2xl text-[15px] leading-[1.75] text-neutral-400">
                {item.answer}
              </p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQBlock;